export const FlowWagePayrollEscrowABI = [
  {
    inputs: [
      { name: '_usdc', type: 'address' },
      { name: '_feeManager', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'runId', type: 'bytes32' },
      { indexed: true, name: 'employer', type: 'address' },
      { indexed: false, name: 'totalAmount', type: 'uint256' },
      { indexed: false, name: 'workerCount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'PayrollCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'runId', type: 'bytes32' },
      { indexed: true, name: 'paymentId', type: 'bytes32' },
      { indexed: true, name: 'worker', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'PaymentReleased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'runId', type: 'bytes32' },
      { indexed: true, name: 'paymentId', type: 'bytes32' },
      { indexed: true, name: 'worker', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'PaymentClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'runId', type: 'bytes32' },
      { indexed: true, name: 'paymentId', type: 'bytes32' },
      { indexed: true, name: 'worker', type: 'address' },
      { indexed: false, name: 'reason', type: 'string' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'PaymentDisputed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'runId', type: 'bytes32' },
      { indexed: true, name: 'paymentId', type: 'bytes32' },
      { indexed: false, name: 'resolved', type: 'bool' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'DisputeResolved',
    type: 'event',
  },
  {
    inputs: [
      { name: 'workers', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'payPeriodLabel', type: 'string' },
    ],
    name: 'createPayroll',
    outputs: [{ name: 'runId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'paymentId', type: 'bytes32' }],
    name: 'claimPayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'paymentId', type: 'bytes32' },
      { name: 'reason', type: 'string' },
    ],
    name: 'disputePayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'paymentId', type: 'bytes32' },
      { name: 'releaseToWorker', type: 'bool' },
    ],
    name: 'resolveDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'runId', type: 'bytes32' }],
    name: 'getPayrollRun',
    outputs: [
      {
        components: [
          { name: 'employer', type: 'address' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'workerCount', type: 'uint256' },
          { name: 'claimedCount', type: 'uint256' },
          { name: 'payPeriodLabel', type: 'string' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'status', type: 'uint8' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'paymentId', type: 'bytes32' }],
    name: 'getPayment',
    outputs: [
      {
        components: [
          { name: 'runId', type: 'bytes32' },
          { name: 'worker', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'claimedAt', type: 'uint256' },
          { name: 'disputeReason', type: 'string' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'worker', type: 'address' }],
    name: 'getPendingPayments',
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'employer', type: 'address' }],
    name: 'getEmployerRuns',
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'disputeWindow',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
