export const FlowLedgerMultisigABI = [
  {
    inputs: [{ name: '_usdc', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'teamId', type: 'bytes32' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'signerCount', type: 'uint256' },
      { indexed: false, name: 'requiredApprovals', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'TeamCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposalId', type: 'bytes32' },
      { indexed: true, name: 'teamId', type: 'bytes32' },
      { indexed: true, name: 'proposer', type: 'address' },
      { indexed: false, name: 'totalAmount', type: 'uint256' },
      { indexed: false, name: 'label', type: 'string' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'ProposalCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposalId', type: 'bytes32' },
      { indexed: true, name: 'signer', type: 'address' },
      { indexed: false, name: 'approvalCount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'ProposalApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposalId', type: 'bytes32' },
      { indexed: false, name: 'totalAmount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'ProposalExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'proposalId', type: 'bytes32' },
      { indexed: false, name: 'refunded', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'ProposalCancelled',
    type: 'event',
  },
  {
    inputs: [
      { name: 'signers', type: 'address[]' },
      { name: 'requiredApprovals', type: 'uint256' },
    ],
    name: 'createTeam',
    outputs: [{ name: 'teamId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'teamId', type: 'bytes32' },
      { name: 'workers', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'label', type: 'string' },
    ],
    name: 'createProposal',
    outputs: [{ name: 'proposalId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'proposalId', type: 'bytes32' }],
    name: 'approveProposal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'proposalId', type: 'bytes32' }],
    name: 'cancelProposal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'teamId', type: 'bytes32' }],
    name: 'getTeam',
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'signers', type: 'address[]' },
      { name: 'requiredApprovals', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'proposalId', type: 'bytes32' }],
    name: 'getProposal',
    outputs: [
      { name: 'teamId', type: 'bytes32' },
      { name: 'proposer', type: 'address' },
      { name: 'workers', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
      { name: 'label', type: 'string' },
      { name: 'totalAmount', type: 'uint256' },
      { name: 'approvalCount', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'teamId', type: 'bytes32' }],
    name: 'getTeamProposals',
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'getUserTeams',
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
