export const FlowLedgerBountiesABI = [
  {
    inputs: [{ name: '_usdc', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'bountyId', type: 'bytes32' },
      { indexed: true, name: 'employer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'descriptionHash', type: 'bytes32' },
      { indexed: false, name: 'deadline', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'BountyCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'bountyId', type: 'bytes32' },
      { indexed: true, name: 'submitter', type: 'address' },
      { indexed: false, name: 'proofHash', type: 'bytes32' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'WorkSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'bountyId', type: 'bytes32' },
      { indexed: true, name: 'submitter', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'BountyApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'bountyId', type: 'bytes32' },
      { indexed: true, name: 'submitter', type: 'address' },
      { indexed: false, name: 'reasonHash', type: 'bytes32' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'SubmissionRejected',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'bountyId', type: 'bytes32' },
      { indexed: false, name: 'refunded', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'BountyCancelled',
    type: 'event',
  },
  {
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'descriptionHash', type: 'bytes32' },
      { name: 'deadline', type: 'uint256' },
    ],
    name: 'createBounty',
    outputs: [{ name: 'bountyId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'bountyId', type: 'bytes32' },
      { name: 'proofHash', type: 'bytes32' },
    ],
    name: 'submitWork',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'bountyId', type: 'bytes32' },
      { name: 'submitter', type: 'address' },
    ],
    name: 'approveBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'bountyId', type: 'bytes32' },
      { name: 'submitter', type: 'address' },
      { name: 'reasonHash', type: 'bytes32' },
    ],
    name: 'rejectSubmission',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'bountyId', type: 'bytes32' }],
    name: 'cancelBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'bountyId', type: 'bytes32' }],
    name: 'getBounty',
    outputs: [
      { name: 'employer', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'descriptionHash', type: 'bytes32' },
      { name: 'deadline', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'approvedSubmitter', type: 'address' },
      { name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'bountyId', type: 'bytes32' },
      { name: 'submitter', type: 'address' },
    ],
    name: 'getSubmission',
    outputs: [
      { name: 'proofHash', type: 'bytes32' },
      { name: 'submittedAt', type: 'uint256' },
      { name: 'status', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'bountyId', type: 'bytes32' }],
    name: 'getBountySubmitters',
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'employer', type: 'address' }],
    name: 'getEmployerBounties',
    outputs: [{ name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
